// AUTO-GENERATED by scripts/image-dims.mjs — do not edit by hand.
// Re-run: node scripts/image-dims.mjs --write
export type ImageDims = { w: number; h: number };

const DIMS: Record<string, ImageDims> = {
  'images/events/biblo-boyama.jpeg': { w: 1080, h: 1350 },
  'images/events/camping.jpeg': { w: 1080, h: 1350 },
  'images/events/canta-boyama.jpeg': { w: 1080, h: 1350 },
  'images/events/hiking.jpeg': { w: 1080, h: 1350 },
  'images/events/kil-boyama.jpeg': { w: 1080, h: 1350 },
  'images/events/kitap-soylesisi.jpeg': { w: 1080, h: 1350 },
  'images/events/speaking-club.jpeg': { w: 960, h: 1205 },
  'images/logo/kocaeli-logo.jpeg': { w: 640, h: 640 },
};

/**
 * Intrinsic pixel size of a local image (public/images), or undefined for
 * anything that is not a bundled image (remote URLs, SVG, ...).
 */
export function imageDims(src: string): ImageDims | undefined {
  if (!src) return undefined;
  const match = /images\/[a-z0-9._/-]+\.(?:jpe?g|png|webp|gif)$/i.exec(src);
  if (!match) return undefined;
  return DIMS[match[0]];
}
