#!/usr/bin/env node
// Dependency-free JPEG/PNG intrinsic-dimension reader for public/images.
// Usage: node scripts/image-dims.mjs [--write]
//   --write  also (re)generate src/utils/imageDims.ts

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const imagesDir = path.join(root, 'public', 'images');
const outFile = path.join(root, 'src', 'utils', 'imageDims.ts');

function jpegDims(buf) {
  // SOI marker, then length-prefixed segments until an SOFn frame header.
  if (buf[0] !== 0xff || buf[1] !== 0xd8) return null;
  let i = 2;
  while (i + 9 < buf.length) {
    if (buf[i] !== 0xff) {
      i += 1;
      continue;
    }
    const marker = buf[i + 1];
    if (marker === 0xff) {
      i += 1;
      continue;
    }
    // Standalone markers carry no length field.
    if (marker === 0x01 || (marker >= 0xd0 && marker <= 0xd9)) {
      i += 2;
      continue;
    }
    const len = buf.readUInt16BE(i + 2);
    if (len < 2) return null;
    const isFrame =
      marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc;
    if (isFrame) {
      return { h: buf.readUInt16BE(i + 5), w: buf.readUInt16BE(i + 7) };
    }
    i += 2 + len;
  }
  return null;
}

function pngDims(buf) {
  const sig = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
  if (buf.length < 24 || !sig.every((b, k) => buf[k] === b)) return null;
  if (buf.toString('ascii', 12, 16) !== 'IHDR') return null;
  return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
}

function readDims(file) {
  const buf = readFileSync(file);
  const lower = file.toLowerCase();
  if (lower.endsWith('.png')) return pngDims(buf);
  if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return jpegDims(buf);
  return pngDims(buf) || jpegDims(buf);
}

function walk(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

const files = walk(imagesDir).sort();
const rows = [];
for (const file of files) {
  const rel = path.relative(root, file).split(path.sep).join('/');
  const key = rel.replace(/^public\//, '');
  const dims = readDims(file);
  if (!dims || !dims.w || !dims.h) {
    rows.push({ key, rel, w: 0, h: 0, ok: false });
    continue;
  }
  rows.push({ key, rel, w: dims.w, h: dims.h, ok: true });
}

const pad = (s, n) => String(s).padEnd(n);
console.log(pad('file', 44) + pad('width', 8) + 'height');
for (const r of rows) {
  console.log(pad(r.key, 44) + pad(r.ok ? r.w : 'ERR', 8) + (r.ok ? r.h : 'ERR'));
}
const failed = rows.filter((r) => !r.ok);
if (failed.length) {
  console.error(`\nFAILED: ${failed.length} unreadable image(s): ${failed.map((f) => f.key).join(', ')}`);
  process.exit(1);
}

if (process.argv.includes('--write')) {
  const lines = rows.map(
    (r) => `  '${r.key}': { w: ${r.w}, h: ${r.h} },`
  );
  const source = `// AUTO-GENERATED by scripts/image-dims.mjs — do not edit by hand.
// Re-run: node scripts/image-dims.mjs --write
export type ImageDims = { w: number; h: number };

const DIMS: Record<string, ImageDims> = {
${lines.join('\n')}
};

/**
 * Intrinsic pixel size of a local image (public/images), or undefined for
 * anything that is not a bundled image (remote URLs, SVG, ...).
 */
export function imageDims(src: string): ImageDims | undefined {
  if (!src) return undefined;
  const match = /images\\/[a-z0-9._/-]+\\.(?:jpe?g|png|webp|gif)$/i.exec(src);
  if (!match) return undefined;
  return DIMS[match[0]];
}
`;
  writeFileSync(outFile, source);
  console.log(`\nwrote ${path.relative(root, outFile)} (${rows.length} entries)`);
}
